# vim:sw=2:et:

sudo: false
language: generic
notifications:
  email:
    recipients:
      - alerts@rabbitmq.com
    on_success: never
    on_failure: always

addons:
  apt:
    sources:
      - sourceline: deb https://packages.erlang-solutions.com/ubuntu trusty contrib
        key_url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
    packages:
      - awscli
      - elixir=1.6.6-2
      - erlang-common-test
      - erlang-dev
      - erlang-dialyzer
      - erlang-eunit

cache:
  apt: true
env:
  global:
    - secure: YQ5QmZHQC3dBIk0vfHlQxHejaqCLq6GbuinOgLieS/Vwrmt51zbg+Wf/tG5yNTaYHHBev/D2e1u2nidZPQ6Xg4InFuknr2dYyPeJ+6A6194aWvdOkB/O3Ii2+m3dafZxsmYj9SZPYIUcwyzXQHwyaL/zOUJC9MGQzYv1L1FAQnQ=
    - secure: Q1Du4xVNhvNBSv7vYzcF/9HB7R85nhwIpjZogfbZM2Kr6oTOeT8lyCEoiDjbiXkxZdWQa2YVGsjcvz8Q4rDvt8xu1gUG8j/bV3QWjB+0iWq2xQotnKvXW/toiDKBYyoIj9RUrQR5brwU95R1GAClLqxMdjY+/LijzLKqlQQo1L4=

before_script:
  # Make sure we use Elixir from Erlang Solutions and not kiex.
  - |
    echo YES | kiex implode
    elixir --version
    elixir --version | grep -q 'Elixir 1.6.6'

script:
  - make tests
  - make xref
  - make dialyze

after_failure:
  - |
    cd "$TRAVIS_BUILD_DIR"
    if test -d logs && test "$AWS_ACCESS_KEY_ID" && test "$AWS_SECRET_ACCESS_KEY"; then
      archive_name="$(basename "$TRAVIS_REPO_SLUG")-$TRAVIS_JOB_NUMBER"

      tar -c --transform "s/^logs/${archive_name}/" -f - logs | \
        xz > "${archive_name}.tar.xz"

      aws s3 cp "${archive_name}.tar.xz" s3://server-release-pipeline/travis-ci-logs/ \
        --region eu-west-1 \
        --acl public-read
    fi
