# vim:sw=2:et:

os: linux
dist: bionic
sudo: false

language: erlang
notifications:
  email:
    on_success: never
    on_failure: always

otp_release:
otp_release:
  - "23.0.2"
  - "22.3.4"

script:
  - make xref
  - make check
  - make dialyze
